package org.fogbowcloud.saps.engine.core.pojo;

import org.fogbowcloud.saps.engine.core.model.ImageTask;

/**
 * Holds the information of a file generated by the processing of a {@link ImageTask}.
 */
public class ImageTaskFile {

    private String path;
    private String name;
    private String URL;

    public ImageTaskFile(String path, String name) {
        this(path, name, null);
    }

    public ImageTaskFile(String path, String name, String URL) {
        this.path = path;
        this.name = name;
        this.URL = URL;
    }

    public String getPath() {
        return path;
    }

    public String getName() {
        return name;
    }

    public String getURL() {
        return URL;
    }

    public void setURL(String URL) {
        this.URL = URL;
    }
}
