package org.fogbowcloud.saps.engine.core.pojo;

import org.fogbowcloud.saps.engine.core.model.ImageTask;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Holds the information of a file generated by the processing of a {@link ImageTask}.
 */
public class ImageTaskFile {

    private static final String NAME_KEY = "name";
    private static final String URL_KEY = "url";

    private String path;
    private String name;
    private String URL;

    public ImageTaskFile(String path, String name) {
        this(path, name, null);
    }

    public ImageTaskFile(String path, String name, String URL) {
        this.path = path;
        this.name = name;
        this.URL = URL;
    }

    public ImageTaskFile(JSONObject jsonObject) throws JSONException {
        this(null,
                jsonObject.getString(NAME_KEY),
                jsonObject.getString(URL_KEY));
    }

    public JSONObject toJSON() throws JSONException {
        JSONObject imageTaskFileJSONObject = new JSONObject();
        imageTaskFileJSONObject.put(NAME_KEY, name);
        imageTaskFileJSONObject.put(URL_KEY, URL);
        return  imageTaskFileJSONObject;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getURL() {
        return URL;
    }

    public void setURL(String URL) {
        this.URL = URL;
    }

}
